# options

In [44]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Imports

In [45]:
import pandas as pd
import matplotlib.pyplot as plt

# Exercise 0 - Read the data

the file is under the folder data and is named `supermarket_sales_V2.csv`

In [46]:

 url = "https://raw.githubusercontent.com/samsung-ai-course/6-7-edition/refs/heads/main/Data%20Wrangling/Data%20Wrangling%20-%20Pandas-Advanced/Data%20Analysis%20Advanced/data/supermarket_sales_V2.csv"
 df = pd.read_csv(url)
 df.head(3)
 df.shape

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,cogs,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,1/5/2019,13:08,Ewallet,522.83,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3/8/2019,10:29,Cash,76.40,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,3/3/2019,13:23,Credit card,324.31,7.4

(1000, 13)

This data contains the necessary info to compute the remaining columns:

# Exercise 1 - Creating new columns

## Exercise 1.1

create a new column `Total (Before Taxes)` that represents the cost of the purchase before taxes obtained by multiplying the `quantity` by the `unit price`

In [47]:

 total_before_taxes = df['Unit price'] * df['Quantity']
 df['Total (Before Taxes)'] = total_before_taxes

 df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,cogs,Rating,Total (Before Taxes)
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,1/5/2019,13:08,Ewallet,522.83,9.1,522.83
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3/8/2019,10:29,Cash,76.40,9.6,76.40
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,3/3/2019,13:23,Credit card,324.31,7.4,324.31
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,1/27/2019,20:33,Ewallet,465.76,8.4,465.76
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,2/8/2019,10:37,Ewallet,604.17,5.3,604.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,1/29/2019,13:46,Ewallet,40.35,6.2,40.35
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,3/2/2019,17:16,Ewallet,973.80,4.4,973.80
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,2/9/2019,13:22,Cash,31.84,7.7,31.84
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,2/22/2019,15:33,Cash,65.82,4.1,65.82
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,2/18/2019,13:28,Cash,618.38,6.6,618.38

## Exercise 1.2

> Create a new column `Tax 7%` that represents a 7% of the `Total (Before Taxes)`

In [48]:
 tax_7 = total_before_taxes.apply(lambda row: row * 0.07)

 df['Tax 7%'] = tax_7
 df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,cogs,Rating,Total (Before Taxes),Tax 7%
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,1/5/2019,13:08,Ewallet,522.83,9.1,522.83,36.5981
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3/8/2019,10:29,Cash,76.40,9.6,76.40,5.3480
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,3/3/2019,13:23,Credit card,324.31,7.4,324.31,22.7017
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,1/27/2019,20:33,Ewallet,465.76,8.4,465.76,32.6032
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,2/8/2019,10:37,Ewallet,604.17,5.3,604.17,42.2919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,1/29/2019,13:46,Ewallet,40.35,6.2,40.35,2.8245
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,3/2/2019,17:16,Ewallet,973.80,4.4,973.80,68.1660
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,2/9/2019,13:22,Cash,31.84,7.7,31.84,2.2288
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,2/22/2019,15:33,Cash,65.82,4.1,65.82,4.6074
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,2/18/2019,13:28,Cash,618.38,6.6,618.38,43.2866

## Exercise 1.3
> Create a new column `Total` that represents the `Total (Before Taxes)` added with the `Tax 7%`

In [49]:
 #df['day'] = df['Date'].apply(lambda row: row.split('/')[1])
 df['Total'] = df['Total (Before Taxes)']+df['Tax 7%']
 df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,cogs,Rating,Total (Before Taxes),Tax 7%,Total
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,1/5/2019,13:08,Ewallet,522.83,9.1,522.83,36.5981,559.4281
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3/8/2019,10:29,Cash,76.40,9.6,76.40,5.3480,81.7480
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,3/3/2019,13:23,Credit card,324.31,7.4,324.31,22.7017,347.0117
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,1/27/2019,20:33,Ewallet,465.76,8.4,465.76,32.6032,498.3632
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,2/8/2019,10:37,Ewallet,604.17,5.3,604.17,42.2919,646.4619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,1/29/2019,13:46,Ewallet,40.35,6.2,40.35,2.8245,43.1745
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,3/2/2019,17:16,Ewallet,973.80,4.4,973.80,68.1660,1041.9660
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,2/9/2019,13:22,Cash,31.84,7.7,31.84,2.2288,34.0688
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,2/22/2019,15:33,Cash,65.82,4.1,65.82,4.6074,70.4274
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,2/18/2019,13:28,Cash,618.38,6.6,618.38,43.2866,661.6666

## Exercise 1.4
> Create a new column `gross income` that represents the Total minus the cost of goods sold `cogs`

In [50]:
 df['gross income'] = df['Total']-df['cogs']
 df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,cogs,Rating,Total (Before Taxes),Tax 7%,Total,gross income
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,1/5/2019,13:08,Ewallet,522.83,9.1,522.83,36.5981,559.4281,36.5981
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3/8/2019,10:29,Cash,76.40,9.6,76.40,5.3480,81.7480,5.3480
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,3/3/2019,13:23,Credit card,324.31,7.4,324.31,22.7017,347.0117,22.7017
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,1/27/2019,20:33,Ewallet,465.76,8.4,465.76,32.6032,498.3632,32.6032
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,2/8/2019,10:37,Ewallet,604.17,5.3,604.17,42.2919,646.4619,42.2919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,1/29/2019,13:46,Ewallet,40.35,6.2,40.35,2.8245,43.1745,2.8245
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,3/2/2019,17:16,Ewallet,973.80,4.4,973.80,68.1660,1041.9660,68.1660
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,2/9/2019,13:22,Cash,31.84,7.7,31.84,2.2288,34.0688,2.2288
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,2/22/2019,15:33,Cash,65.82,4.1,65.82,4.6074,70.4274,4.6074
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,2/18/2019,13:28,Cash,618.38,6.6,618.38,43.2866,661.6666,43.2866

## Exercise 1.5
> Create a new column `gross margin percentage` that represents the `gross income` as a percentage of the `Total`

In [51]:
 df['gross margin percentage'] = df['gross income']/ df['Total']  * 100
 df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,cogs,Rating,Total (Before Taxes),Tax 7%,Total,gross income,gross margin percentage
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,1/5/2019,13:08,Ewallet,522.83,9.1,522.83,36.5981,559.4281,36.5981,6.542056
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3/8/2019,10:29,Cash,76.40,9.6,76.40,5.3480,81.7480,5.3480,6.542056
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,3/3/2019,13:23,Credit card,324.31,7.4,324.31,22.7017,347.0117,22.7017,6.542056
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,1/27/2019,20:33,Ewallet,465.76,8.4,465.76,32.6032,498.3632,32.6032,6.542056
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,2/8/2019,10:37,Ewallet,604.17,5.3,604.17,42.2919,646.4619,42.2919,6.542056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,1/29/2019,13:46,Ewallet,40.35,6.2,40.35,2.8245,43.1745,2.8245,6.542056
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,3/2/2019,17:16,Ewallet,973.80,4.4,973.80,68.1660,1041.9660,68.1660,6.542056
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,2/9/2019,13:22,Cash,31.84,7.7,31.84,2.2288,34.0688,2.2288,6.542056
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,2/22/2019,15:33,Cash,65.82,4.1,65.82,4.6074,70.4274,4.6074,6.542056
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,2/18/2019,13:28,Cash,618.38,6.6,618.38,43.2866,661.6666,43.2866,6.542056

## Exercise 1.6
> Create a new column `hour` that is the hour of the day extracted from the column `Time`

In [52]:

 df['hour'] = df['Time'].apply(lambda row: row.split(':')[0])
 df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,cogs,Rating,Total (Before Taxes),Tax 7%,Total,gross income,gross margin percentage,hour
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,1/5/2019,13:08,Ewallet,522.83,9.1,522.83,36.5981,559.4281,36.5981,6.542056,13
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3/8/2019,10:29,Cash,76.40,9.6,76.40,5.3480,81.7480,5.3480,6.542056,10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,3/3/2019,13:23,Credit card,324.31,7.4,324.31,22.7017,347.0117,22.7017,6.542056,13
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,1/27/2019,20:33,Ewallet,465.76,8.4,465.76,32.6032,498.3632,32.6032,6.542056,20
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,2/8/2019,10:37,Ewallet,604.17,5.3,604.17,42.2919,646.4619,42.2919,6.542056,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,1/29/2019,13:46,Ewallet,40.35,6.2,40.35,2.8245,43.1745,2.8245,6.542056,13
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,3/2/2019,17:16,Ewallet,973.80,4.4,973.80,68.1660,1041.9660,68.1660,6.542056,17
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,2/9/2019,13:22,Cash,31.84,7.7,31.84,2.2288,34.0688,2.2288,6.542056,13
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,2/22/2019,15:33,Cash,65.82,4.1,65.82,4.6074,70.4274,4.6074,6.542056,15
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,2/18/2019,13:28,Cash,618.38,6.6,618.38,43.2866,661.6666,43.2866,6.542056,13

# Exercise 2 - Masking

## Exercise 2.1
> What is the median payment gross income the supermarket company has from men?

In [53]:
 gross_income_from_men = df['Gender'] == 'Male'
 df.loc[gross_income_from_men,'gross income'].median()

16.28200000000001

## Exercise 2.2
> How many purchases does the store in City `Mandalay` have?

In [54]:
 n_purchases_mandalay = (df['City'] == 'Mandalay').sum()
 n_purchases_mandalay

np.int64(332)

In [55]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,cogs,Rating,Total (Before Taxes),Tax 7%,Total,gross income,gross margin percentage,hour
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,1/5/2019,13:08,Ewallet,522.83,9.1,522.83,36.5981,559.4281,36.5981,6.542056,13
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3/8/2019,10:29,Cash,76.40,9.6,76.40,5.3480,81.7480,5.3480,6.542056,10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,3/3/2019,13:23,Credit card,324.31,7.4,324.31,22.7017,347.0117,22.7017,6.542056,13
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,1/27/2019,20:33,Ewallet,465.76,8.4,465.76,32.6032,498.3632,32.6032,6.542056,20
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,2/8/2019,10:37,Ewallet,604.17,5.3,604.17,42.2919,646.4619,42.2919,6.542056,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,1/29/2019,13:46,Ewallet,40.35,6.2,40.35,2.8245,43.1745,2.8245,6.542056,13
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,3/2/2019,17:16,Ewallet,973.80,4.4,973.80,68.1660,1041.9660,68.1660,6.542056,17
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,2/9/2019,13:22,Cash,31.84,7.7,31.84,2.2288,34.0688,2.2288,6.542056,13
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,2/22/2019,15:33,Cash,65.82,4.1,65.82,4.6074,70.4274,4.6074,6.542056,15
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,2/18/2019,13:28,Cash,618.38,6.6,618.38,43.2866,661.6666,43.2866,6.542056,13

## Exercise 2.3

> What is the average rating of `Member` costumers in the store `Yangon`

In [59]:
 avg_rating_member_yagon = df['City'] =='Yangon'
 avg_rating_member_yagon123 =  df['Customer type']== "Member"
 df.loc[avg_rating_member_yagon & avg_rating_member_yagon123,'Rating'].mean()

 #gross_income_from_men = df['Gender'] == 'Male'
 #df.loc[gross_income_from_men,'gross income'].median()

np.float64(6.99880239520958)

## Exercise 2.4
what is the `Invoice ID` of the the most expensive purchase (`Total`) made in the morning (in other words: until, not including, 12 o´clock)

In [ ]:
 invoice_id =

## Exercise 2.5
> What is the product line `Women` buy most often at night (between 19h and 24h, all inclusive)

In [ ]:
# ...

## Exercise 2.6
> How many purchases were made by women in both `Health and beauty` and `Home and Lifestyle` `Product lines`?

In [ ]:
# n_purchases =

# Exercise 3 - Groupbys

## Exercise 3.1
> what is the average `Total` by gender?

In [ ]:
# ...

## Exercise 3.1 b)
> use a bar plot to show the previous result

In [ ]:
# ...

## Exercise 3.2
> What is the average Rating by City?

In [ ]:
# ...

## Exercise 3.2 b)
> use a bar plot to show the previous result

In [ ]:
# ...

## Exercise 3.3
> What is the `Product line` that sells most items (i.e. `Quantities`)

In [ ]:
# ...

## Exercise 3.4
> What is the activity of customers throughout the day?

Compute the number of invoices at each hour of the day

In [ ]:
# ...

## Exercise 3.4 b)
> use a bar plot to show the previous result

In [ ]:
# ...

## Exercise 3.5
> For each city, what is the `Invoice ID` of the highest `gross margin` sale?

In [ ]:
# ...

## Exercise 3.6

> For each customer type, what is the average rating on each Product line?

Try passing a list of columns to the `.groupby` method, and compute the average `rating` of that groupby